"""TINY SYNTHETIC FIXTURES shaped like each real dataset.

These exist so the adapters can be TESTED without the real archives, and so a
first real run is a mechanical step rather than a research step. Running the
pipeline against a fixture found a live specification bug in Round 16
(self-correction 26), which is the strongest possible argument for having them.

EVERY FIXTURE IS SYNTHETIC. A fixture directory is written with a marker file
``_SYNTHETIC_FIXTURE`` so that neither a human nor the pipeline can mistake one
for a real archive; ``aedt.pipeline`` reads that marker and refuses to stamp
results REAL when it is present.

PORTED from ``final_audit.py::make_fixture`` (Round 16).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
import pandas as pd

from ..constants import STRESS_LABEL_TO_SEVERITY, SEED, normalise_label

__all__ = ["FIXTURE_MARKER", "is_fixture", "make_studentlife_fixture",
           "make_pmdata_fixture", "make_relax_fixture"]

FIXTURE_MARKER = "_SYNTHETIC_FIXTURE"


def is_fixture(root) -> bool:
    """True when this directory is a synthetic fixture, not a real archive."""
    if root is None:
        return False
    p = Path(root)
    return (p / FIXTURE_MARKER).exists()


def _mark(root: Path, what: str) -> None:
    (root / FIXTURE_MARKER).write_text(
        f"SYNTHETIC FIXTURE -- {what}\n"
        "This directory was generated by aedt.io.fixtures. It contains NO real "
        "participant data. Any result computed from it is SYNTHETIC and must "
        "be labelled as such.\n")


def make_studentlife_fixture(out_root: str | Path, *, n_participants: int = 24,
                             days: int = 70, seed: int = SEED,
                             scramble_option_order: bool = True) -> Path:
    """A StudentLife-shaped directory, with the response options DELIBERATELY
    stored out of severity order so the label-text remap is exercised."""
    root = Path(out_root)
    rng = np.random.default_rng(seed)
    (root / "EMA" / "response" / "Stress").mkdir(parents=True, exist_ok=True)
    (root / "sensing" / "conversation").mkdir(parents=True, exist_ok=True)

    options = (["A little stressed", "Definitely stressed", "Stressed out",
                "Feeling good", "Feeling great"] if scramble_option_order else
               ["Feeling great", "Feeling good", "A little stressed",
                "Definitely stressed", "Stressed out"])
    ema_def = {"Stress": {"title": "Right now I am ...", "responses": options}}
    (root / "EMA" / "EMA_definition.json").write_text(json.dumps(ema_def, indent=2))

    sev_to_code = {STRESS_LABEL_TO_SEVERITY[normalise_label(lab)]: i
                   for i, lab in enumerate(options, start=1)}
    t0 = pd.Timestamp("2013-03-27")
    for i in range(n_participants):
        pid = f"u{i:02d}"
        lam = rng.uniform(0.4, 0.9)
        n = days * 5
        t = t0 + pd.to_timedelta(np.sort(rng.uniform(0, days, n)), unit="D")
        theta = rng.normal(0, 1, n)
        # conversation minutes FALL as stress rises -- the negative-slope case
        conv = np.clip(60 + 25 * (-lam * theta) + rng.normal(0, 20, n), 0, None)
        latent = theta + rng.normal(0, 0.5, n)
        cuts = np.quantile(latent, [.45, .70, .86, .95])
        sev = np.searchsorted(cuts, latent) + 1
        codes = [sev_to_code[int(v)] for v in sev]
        recs = [{"resp_time": str(int(ts.timestamp())), "level": str(c)}
                for ts, c in zip(t, codes)]
        (root / "EMA" / "response" / "Stress" / f"Stress_{pid}.json").write_text(
            json.dumps(recs))
        dstart = (t.normalize().astype("int64") // 10 ** 9).to_numpy()
        pd.DataFrame({"start_timestamp": dstart,
                      "end_timestamp": dstart + (conv * 60).astype(int)}
                     ).to_csv(root / "sensing" / "conversation" /
                              f"conversation_{pid}.csv", index=False)
    _mark(root, f"StudentLife-shaped, {n_participants} participants, {days} days")
    return root


def make_pmdata_fixture(out_root: str | Path, *, n_participants: int = 12,
                        days: int = 150, seed: int = SEED) -> Path:
    """A PMData-shaped directory: pmsys/wellness.csv + fitbit resting HR."""
    root = Path(out_root)
    rng = np.random.default_rng(seed + 1)
    t0 = pd.Timestamp("2019-11-01")
    for i in range(1, n_participants + 1):
        pid = f"p{i:02d}"
        (root / pid / "pmsys").mkdir(parents=True, exist_ok=True)
        (root / pid / "fitbit").mkdir(parents=True, exist_ok=True)
        d = t0 + pd.to_timedelta(np.arange(days), unit="D")
        theta = rng.normal(0, 1, days)
        hr = 58 + 6 * theta + rng.normal(0, 3, days)
        latent = theta + rng.normal(0, 0.5, days)
        cuts = np.quantile(latent, [.25, .50, .75, .90])
        stress = np.searchsorted(cuts, latent) + 1
        pd.DataFrame({"effective_time_frame": d.strftime("%Y-%m-%d"),
                      "fatigue": rng.integers(1, 6, days),
                      "stress": stress}).to_csv(
            root / pid / "pmsys" / "wellness.csv", index=False)
        (root / pid / "fitbit" / "resting_heart_rate.json").write_text(
            json.dumps([{"dateTime": ts.strftime("%Y-%m-%d"),
                         "value": {"value": float(v), "error": 0.0}}
                        for ts, v in zip(d, hr)]))
    _mark(root, f"PMData-shaped, {n_participants} participants, {days} days")
    return root


def make_relax_fixture(out_root: str | Path, *, n_participants: int = 16,
                       days: int = 60, reports_per_day: int = 3,
                       seed: int = SEED) -> Path:
    """A RELAX-shaped directory under the DECLARED expected layout."""
    root = Path(out_root)
    root.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed + 2)
    t0 = pd.Timestamp("2022-05-01")
    rep_rows, phys_rows = [], []
    for i in range(1, n_participants + 1):
        pid = f"P{i:02d}"
        n = days * reports_per_day
        ts = t0 + pd.to_timedelta(np.sort(rng.uniform(0, days * 24, n)), unit="h")
        theta = rng.normal(0, 1, n)
        latent = theta + rng.normal(0, 0.5, n)
        cuts = np.quantile(latent, [.30, .55, .78, .92])
        rep_rows.append(pd.DataFrame({
            "participant_id": pid, "timestamp": ts,
            "stress": np.searchsorted(cuts, latent) + 1}))
        # physiology sampled 30 min before each report, inside the causal window
        phys_rows.append(pd.DataFrame({
            "participant_id": pid,
            "timestamp": ts - pd.Timedelta(minutes=30),
            "hr": 62 + 7 * theta + rng.normal(0, 2.5, n)}))
    pd.concat(rep_rows, ignore_index=True).to_csv(root / "stress_report.csv",
                                                  index=False)
    pd.concat(phys_rows, ignore_index=True).to_csv(root / "wearable_physio.csv",
                                                   index=False)
    _mark(root, f"RELAX-shaped, {n_participants} participants, {days} days")
    return root
