"""TINY SYNTHETIC FIXTURES shaped like each real dataset.

These exist so the adapters can be TESTED without the real archives, and so a
first real run is a mechanical step rather than a research step. Running the
pipeline against a fixture found a live specification bug in Round 16
(self-correction 26), which is the strongest possible argument for having them.

EVERY FIXTURE IS SYNTHETIC. A fixture directory is written with a marker file
``_SYNTHETIC_FIXTURE`` so that neither a human nor the pipeline can mistake one
for a real archive; ``aedt.pipeline`` reads that marker and refuses to stamp
results REAL when it is present.

PORTED from ``final_audit.py::make_fixture`` (Round 16).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
import pandas as pd

from ..constants import STRESS_LABEL_TO_SEVERITY, SEED, normalise_label

__all__ = ["FIXTURE_MARKER", "is_fixture", "make_studentlife_fixture",
           "make_pmdata_fixture", "make_relax_fixture"]

FIXTURE_MARKER = "_SYNTHETIC_FIXTURE"


def is_fixture(root) -> bool:
    """True when this directory is a synthetic fixture, not a real archive."""
    if root is None:
        return False
    p = Path(root)
    return (p / FIXTURE_MARKER).exists()


def _mark(root: Path, what: str) -> None:
    (root / FIXTURE_MARKER).write_text(
        f"SYNTHETIC FIXTURE -- {what}\n"
        "This directory was generated by aedt.io.fixtures. It contains NO real "
        "participant data. Any result computed from it is SYNTHETIC and must "
        "be labelled as such.\n")


def make_studentlife_fixture(out_root: str | Path, *, n_participants: int = 24,
                             days: int = 70, seed: int = SEED,
                             scramble_option_order: bool = True) -> Path:
    """A StudentLife-shaped directory, with the response options DELIBERATELY
    stored out of severity order so the label-text remap is exercised."""
    root = Path(out_root)
    rng = np.random.default_rng(seed)
    (root / "EMA" / "response" / "Stress").mkdir(parents=True, exist_ok=True)
    (root / "sensing" / "conversation").mkdir(parents=True, exist_ok=True)

    options = (["A little stressed", "Definitely stressed", "Stressed out",
                "Feeling good", "Feeling great"] if scramble_option_order else
               ["Feeling great", "Feeling good", "A little stressed",
                "Definitely stressed", "Stressed out"])
    ema_def = {"Stress": {"title": "Right now I am ...", "responses": options}}
    (root / "EMA" / "EMA_definition.json").write_text(json.dumps(ema_def, indent=2))

    sev_to_code = {STRESS_LABEL_TO_SEVERITY[normalise_label(lab)]: i
                   for i, lab in enumerate(options, start=1)}
    t0 = pd.Timestamp("2013-03-27")
    for i in range(n_participants):
        pid = f"u{i:02d}"
        lam = rng.uniform(0.4, 0.9)
        n = days * 5
        t = t0 + pd.to_timedelta(np.sort(rng.uniform(0, days, n)), unit="D")
        theta = rng.normal(0, 1, n)
        # conversation minutes FALL as stress rises -- the negative-slope case
        conv = np.clip(60 + 25 * (-lam * theta) + rng.normal(0, 20, n), 0, None)
        latent = theta + rng.normal(0, 0.5, n)
        cuts = np.quantile(latent, [.45, .70, .86, .95])
        sev = np.searchsorted(cuts, latent) + 1
        codes = [sev_to_code[int(v)] for v in sev]
        recs = [{"resp_time": str(int(ts.timestamp())), "level": str(c)}
                for ts, c in zip(t, codes)]
        (root / "EMA" / "response" / "Stress" / f"Stress_{pid}.json").write_text(
            json.dumps(recs))
        dstart = (t.normalize().astype("int64") // 10 ** 9).to_numpy()
        pd.DataFrame({"start_timestamp": dstart,
                      "end_timestamp": dstart + (conv * 60).astype(int)}
                     ).to_csv(root / "sensing" / "conversation" /
                              f"conversation_{pid}.csv", index=False)
    _mark(root, f"StudentLife-shaped, {n_participants} participants, {days} days")
    return root


def make_pmdata_fixture(out_root: str | Path, *, n_participants: int = 12,
                        days: int = 150, seed: int = SEED) -> Path:
    """A PMData-shaped directory: pmsys/wellness.csv + fitbit resting HR."""
    root = Path(out_root)
    rng = np.random.default_rng(seed + 1)
    t0 = pd.Timestamp("2019-11-01")
    for i in range(1, n_participants + 1):
        pid = f"p{i:02d}"
        (root / pid / "pmsys").mkdir(parents=True, exist_ok=True)
        (root / pid / "fitbit").mkdir(parents=True, exist_ok=True)
        d = t0 + pd.to_timedelta(np.arange(days), unit="D")
        theta = rng.normal(0, 1, days)
        hr = 58 + 6 * theta + rng.normal(0, 3, days)
        latent = theta + rng.normal(0, 0.5, days)
        cuts = np.quantile(latent, [.25, .50, .75, .90])
        stress = np.searchsorted(cuts, latent) + 1
        pd.DataFrame({"effective_time_frame": d.strftime("%Y-%m-%d"),
                      "fatigue": rng.integers(1, 6, days),
                      "stress": stress}).to_csv(
            root / pid / "pmsys" / "wellness.csv", index=False)
        (root / pid / "fitbit" / "resting_heart_rate.json").write_text(
            json.dumps([{"dateTime": ts.strftime("%Y-%m-%d"),
                         "value": {"value": float(v), "error": 0.0}}
                        for ts, v in zip(d, hr)]))
    _mark(root, f"PMData-shaped, {n_participants} participants, {days} days")
    return root


def make_relax_fixture(out_root: str | Path, *, n_participants: int = 14,
                       reports_per_participant: int = 130,
                       seed: int = SEED, item: str = "ifb-2") -> Path:
    """A RELAX-shaped directory matching the VERIFIED release layout.

    Mirrors the real archive exactly: an ``ifb`` response sheet keyed on
    ``user`` / ``manual_date`` (epoch ms) / ``readable_date``, a questionnaire
    definition sheet carrying the ANSWER-LABEL ANCHORS, and per-participant
    ``ibi_data.parquet`` files with ``ibi_ppi`` / ``ibi_blocker`` /
    ``ibi_errorEstimate`` / tz-aware UTC ``timestamp``.

    Deliberately denser than the real release (default 130 reports/participant
    vs a real median of 71) so the adapter can be exercised through the
    eligibility screen and the placebo. The real density failure is a property
    of RELAX, not of this adapter, and is asserted separately against the real
    audit.
    """
    root = Path(out_root)
    (root / "metadata").mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed + 2)
    t0 = pd.Timestamp("2024-02-26 06:00:00")

    # ---- item definitions, with the anchors the adapter verifies against ---
    defs = pd.DataFrame([
        {"question_id": "ifb-1", "question_text": "Meine Stimmung ist:",
         "answer_type": "likert-7", "answer_labels": "['negativ', 'positiv']",
         "answer_text_en": "My current mood is:",
         "answer_labels_en": "['negative', 'positive']"},
        {"question_id": "ifb-2", "question_text": "Ich fühle mich:",
         "answer_type": "likert-7", "answer_labels": "['aufgeregt', 'ruhig']",
         "answer_text_en": "I feel:",
         "answer_labels_en": "['excited', 'calm']"},
        {"question_id": "ifb-7", "question_text": "Meine geistige Anstrengung ist:",
         "answer_type": "likert-7", "answer_labels": "['niedrig', 'hoch']",
         "answer_text_en": "My mental effort is:",
         "answer_labels_en": "['low', 'high']"},
    ])

    rows, ibi_by_pid = [], {}
    for i in range(n_participants):
        pid = 12 + i
        n = reports_per_participant
        # reports every ~8h across the study span
        ts = t0 + pd.to_timedelta(np.sort(rng.uniform(0, n * 8, n)), unit="h")
        theta = rng.normal(0, 1, n)
        # heart rate rises with stress; the stored Likert DESCENDS with stress
        # (7 = 'calm'), so the fixture exercises the reversal too.
        latent = theta + rng.normal(0, 0.5, n)
        cuts = np.quantile(latent, [.15, .32, .5, .68, .85])
        severity = np.searchsorted(cuts, latent) + 1       # 1..6 -> pad to 7
        severity = np.clip(severity, 1, 7)
        raw = 8 - severity                                  # reverse for ifb-2
        for k, c in enumerate(("ifb-1", "ifb-2", "ifb-7")):
            pass
        rows.append(pd.DataFrame({
            "user": pid,
            "manual_date": (ts.astype("int64") // 10 ** 6),
            "readable_date": ts,
            "answers/ifb-1-1": rng.integers(1, 8, n),
            "answers/ifb-2-1": raw,
            "answers/ifb-7-1": np.clip(severity + rng.integers(-1, 2, n), 1, 7),
        }))
        # IBI: one sample every ~1s for 40 min before each report
        parts = []
        for j in range(n):
            m = 200
            hr = 62 + 7 * theta[j] + rng.normal(0, 2.0, m)
            ppi = (60000.0 / hr).round().astype("int32")
            stamps = ts[j] - pd.to_timedelta(rng.uniform(60, 2400, m), unit="s")
            parts.append(pd.DataFrame({
                "ibi_ppi": ppi,
                "ibi_blocker": rng.random(m) < 0.15,
                "ibi_errorEstimate": np.full(m, 30, dtype="int32"),
                "timestamp": stamps.tz_localize("UTC")}))
        ibi_by_pid[pid] = pd.concat(parts).sort_values("timestamp")

    with pd.ExcelWriter(root / "questionnaire_responses.xlsx") as w:
        pd.concat(rows, ignore_index=True).to_excel(w, sheet_name="ifb",
                                                    index=False)
        pd.DataFrame({"id": sorted(ibi_by_pid),
                      "username": [f"U{p}" for p in sorted(ibi_by_pid)]}
                     ).to_excel(w, sheet_name="users", index=False)
    with pd.ExcelWriter(root / "metadata" / "questionnaires.xlsx") as w:
        defs.to_excel(w, sheet_name="ifb", index=False)
    (root / "metadata" / "README.md").write_text(
        "SYNTHETIC RELAX-shaped fixture. Mirrors the released data dictionary: "
        "timestamps are tz-aware UTC; ibi_ppi is in milliseconds; ibi_blocker "
        "flags unreliable detections. No imputation is performed.\n")
    for pid, d in ibi_by_pid.items():
        out = root / "data" / str(pid)
        out.mkdir(parents=True, exist_ok=True)
        d.to_parquet(out / "ibi_data.parquet", index=False)

    _mark(root, f"RELAX-shaped, {n_participants} participants, "
                f"{reports_per_participant} reports each")
    return root
