/**
 * Twin Evolution -- predict, observe, compare, update.
 *
 * This is the page that distinguishes the project from an emotion classifier.
 * It steps through a REAL held-out participant one observation at a time and
 * shows, at each step: the state built from history so far, the prediction made
 * BEFORE the next value is known, then the actual value, then the error, then
 * the updated state.
 *
 * Nothing here is animated fiction. `trajectories.json` is generated by
 * scripts/export_trajectories.py from College Experience test participants the
 * model never trained on, and every prediction shown is the model's real
 * out-of-sample output, computed offline and replayed in order.
 *
 * WRONG PREDICTIONS ARE NOT HIDDEN. One of the three participants is close to
 * unpredictable (r = 0.06), and the page says so. A demo that is always right
 * is less convincing than one that shows the system missing and the error being
 * recorded -- and it is what the ceiling analysis predicts.
 */
import T from "../data/trajectories.json";

const esc = (s) => String(s ?? "").replace(/[&<>"']/g,
  (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

const state = { pid: 0, step: 0 };

/** Everything the twin knows at this point, computed from prior rows ONLY. */
function twinState(series, upto) {
  const seen = series.slice(0, upto + 1).map((r) => r.observed);
  if (!seen.length) return null;
  const mean = seen.reduce((a, b) => a + b, 0) / seen.length;
  const sd = Math.sqrt(seen.reduce((a, b) => a + (b - mean) ** 2, 0) / Math.max(1, seen.length - 1));
  const recent = seen.slice(-5);
  const rmean = recent.reduce((a, b) => a + b, 0) / recent.length;
  let ewma = seen[0];
  for (const v of seen.slice(1)) ewma = 0.5 * v + 0.5 * ewma;
  const last = seen.at(-1);
  const trend = recent.length >= 3
    ? (recent.at(-1) - recent[0] > 0.5 ? "rising"
       : recent.at(-1) - recent[0] < -0.5 ? "falling" : "steady")
    : "not established";
  return {
    n: seen.length, baseline: mean, sd, recentMean: rmean, ewma, last, trend,
    deviation: last - mean,
  };
}

function chart(series, step) {
  const W = 640, H = 210, L = 34, R = 16, TOP = 14, B = 30;
  const n = series.length;
  const x = (i) => L + (i / Math.max(1, n - 1)) * (W - L - R);
  const y = (v) => TOP + (1 - (v - 0.6) / (5.4 - 0.6)) * (H - TOP - B);

  const shown = series.slice(0, step + 1);
  const obs = shown.map((r, i) => `${i ? "L" : "M"}${x(i).toFixed(1)},${y(r.observed).toFixed(1)}`).join(" ");
  const st = twinState(series, step);
  const cur = series[step];
  const nxt = series[step + 1];

  const grid = [1, 2, 3, 4, 5].map((v) =>
    `<line x1="${L}" x2="${W - R}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}" class="g"/>
     <text x="${L - 7}" y="${(y(v) + 4).toFixed(1)}" class="ax" text-anchor="end">${v}</text>`).join("");

  const warmEnd = series.findIndex((r) => !r.warmup);
  const warmBand = warmEnd > 0
    ? `<rect x="${L}" y="${TOP}" width="${(x(warmEnd - 1) - L).toFixed(1)}"
         height="${H - TOP - B}" class="warm"/>
       <text x="${L + 4}" y="${TOP + 12}" class="ax">warm-up</text>` : "";

  const baseline = st ? `<line x1="${L}" x2="${W - R}" y1="${y(st.baseline).toFixed(1)}"
      y2="${y(st.baseline).toFixed(1)}" class="base"/>` : "";

  // the prediction for the NEXT point, drawn before its actual value appears
  let predMark = "";
  if (cur && cur.predicted != null && nxt) {
    const px = x(step + 1), py = y(cur.predicted);
    predMark = `<line x1="${x(step).toFixed(1)}" y1="${y(cur.observed).toFixed(1)}"
        x2="${px.toFixed(1)}" y2="${py.toFixed(1)}" class="predline"/>
      <circle cx="${px.toFixed(1)}" cy="${py.toFixed(1)}" r="5" class="pred"/>`;
    if (state.revealed) {
      const ay = y(nxt.observed);
      predMark += `<line x1="${px.toFixed(1)}" y1="${py.toFixed(1)}"
          x2="${px.toFixed(1)}" y2="${ay.toFixed(1)}" class="err"/>
        <circle cx="${px.toFixed(1)}" cy="${ay.toFixed(1)}" r="4.5" class="actual"/>`;
    }
  }

  return `<svg viewBox="0 0 ${W} ${H}" class="chart" role="img"
      aria-label="Stress reports over time with the twin's prediction for the next point.">
    <style>
      .g{stroke:var(--rule);stroke-width:1}
      .ax{fill:var(--ink-3);font-size:10px;font-family:ui-monospace,monospace}
      .warm{fill:var(--ink);opacity:.05}
      .obs{fill:none;stroke:var(--ink-2);stroke-width:2}
      .base{stroke:var(--accent);stroke-width:1.5;stroke-dasharray:4 4;opacity:.8}
      .predline{stroke:var(--accent);stroke-width:2;stroke-dasharray:4 3}
      .pred{fill:var(--panel);stroke:var(--accent);stroke-width:2.5}
      .actual{fill:var(--ok)}
      .err{stroke:var(--warn);stroke-width:2.5}
      .dot{fill:var(--ink-2)}
    </style>
    ${warmBand}${grid}${baseline}
    <path d="${obs}" class="obs"/>
    ${shown.map((r, i) => `<circle cx="${x(i).toFixed(1)}" cy="${y(r.observed).toFixed(1)}" r="2.6" class="dot"/>`).join("")}
    ${predMark}
    <text x="${(L + W) / 2}" y="${H - 4}" class="ax" text-anchor="middle">observation number</text>
  </svg>`;
}

export function viewEvolution(root) {
  const p = T.participants[state.pid];
  const s = p.series;
  // start after warm-up so a prediction exists immediately
  if (state.step < p.warmup_k) state.step = p.warmup_k;
  const cur = s[state.step];
  const nxt = s[state.step + 1];
  const st = twinState(s, state.step);
  const err = state.revealed && cur.predicted != null && nxt
    ? Math.abs(cur.predicted - nxt.observed) : null;
  const perr = state.revealed && nxt ? Math.abs(cur.observed - nxt.observed) : null;

  root.innerHTML = `
    <div class="panel">
      <header><h3>Twin Evolution</h3>
        <span class="meta">predict → observe → compare → update</span></header>
      <div class="pad">
        <div class="msg ok" style="margin-top:0">
          <b>Real anonymised longitudinal data.</b> ${esc(T._note)}
        </div>
        <div class="form">
          <div class="lbl">Participant</div>
          <div class="ctl"><select id="ev-p">
            ${T.participants.map((q, i) => `<option value="${i}"${i === state.pid ? " selected" : ""}>
              ${esc(q.id)} — ${q.n_observations} observations, ${esc(q.predictability)}</option>`).join("")}
          </select></div>
        </div>
        <p class="hint">This person's own autocorrelation is
          <b>r = ${p.own_autocorrelation}</b>. Across the cohort it ranges from
          −0.24 to 0.69 — which is why the same system does well for some people
          and poorly for others.</p>
      </div>

      <div class="pad" style="padding-top:0">${chart(s, state.step)}</div>

      <div class="gridwrap"><table class="grid">
        <thead><tr><th>Twin state after ${st.n} observations</th><th class="num">Value</th></tr></thead>
        <tbody>
          <tr><th>Personal baseline (their own mean)</th><td class="num">${st.baseline.toFixed(2)}</td></tr>
          <tr><th>Personal variability (SD)</th><td class="num">${st.sd.toFixed(2)}</td></tr>
          <tr><th>Recent level (last 5)</th><td class="num">${st.recentMean.toFixed(2)}</td></tr>
          <tr><th>Weighted recent state (EWMA)</th><td class="num">${st.ewma.toFixed(2)}</td></tr>
          <tr><th>Latest report</th><td class="num">${st.last}</td></tr>
          <tr><th>Deviation from their baseline</th><td class="num">${st.deviation >= 0 ? "+" : ""}${st.deviation.toFixed(2)}</td></tr>
          <tr><th>Recent trajectory</th><td class="num">${st.trend}</td></tr>
        </tbody>
      </table></div>

      <div class="pad">
        ${nxt ? (state.revealed ? `
          <div class="msg ${err <= 1 ? "ok" : "warn"}">
            <b>Predicted ${cur.predicted} · actually ${nxt.observed}
            · ${err === 0 ? "exact" : `off by ${err}`}.</b>
            Persistence predicted ${cur.baseline} (${perr === 0 ? "exact" : `off by ${perr}`}).
            ${err > 1 ? " A miss like this is expected: roughly 89% of day-to-day variation is not predictable from the previous report."
                      : ""}
          </div>
          <p class="hint">The observation is now part of the history, and the
            state above has been recomputed from it.</p>`
          : `<div class="msg">
            <b>The twin predicts <span class="mono">${cur.predicted}</span> for the next report.</b>
            It has not seen that value. Reveal it to compare.</div>`)
        : `<div class="msg">End of this participant's record.</div>`}
      </div>

      <div class="actions">
        <button class="b" id="ev-back"${state.step <= p.warmup_k ? " disabled" : ""}>Back</button>
        ${nxt && !state.revealed
          ? `<button class="b run" id="ev-reveal">Reveal what actually happened</button>`
          : `<button class="b run" id="ev-next"${nxt ? "" : " disabled"}>Next observation</button>`}
        <button class="b" id="ev-reset">Restart</button>
        <span class="hint">Observation ${state.step + 1} of ${s.length}</span>
      </div>
    </div>`;

  const $ = (q) => root.querySelector(q);
  $("#ev-p").addEventListener("change", (e) => {
    state.pid = +e.target.value; state.step = 0; state.revealed = false;
    viewEvolution(root);
  });
  $("#ev-reset").addEventListener("click", () => {
    state.step = p.warmup_k; state.revealed = false; viewEvolution(root);
  });
  $("#ev-back")?.addEventListener("click", () => {
    state.step = Math.max(p.warmup_k, state.step - 1); state.revealed = false;
    viewEvolution(root);
  });
  $("#ev-reveal")?.addEventListener("click", () => {
    state.revealed = true; viewEvolution(root);
  });
  $("#ev-next")?.addEventListener("click", () => {
    if (state.step < s.length - 1) state.step += 1;
    state.revealed = false; viewEvolution(root);
  });
}
